POST   http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": 31,
    "nome" : "Frediney",
    "profissao": "Tecnico de TI"
}

###

GET  http://localhost:3000/user HTTP/1.1
content-type: application/json

###
GET  http://localhost:3000/user/4 HTTP/1.1
content-type: application/json

###
PUT  http://localhost:3000/user/4 HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": 30,
    "nome" : "Fred",
    "profissao": "Tecnico"
}

###
DELETE http://localhost:3000/user/1 HTTP/1.1
content-type: application/json