POST http://localhost:3000/usuarios/create HTTP/1.1
content-type: application/json

{
    "nome": "gabriel",
    "dataNascimento": 2006,
    "senha": 1234
}

###

GET http://localhost:3000/usuarios/read HTTP/1.1
content-type: application/json

###

DELETE http://localhost:3000/usuarios/delete/1 HTTP/1.1
content-type: application/json

###
PUT  http://localhost:3000/usuarios/update/2 HTTP/1.1
content-type: application/json

{
    "nome": "marcius",
    "dataNascimento": 1990,
    "senha": 123456
}