POST   http://10.60.46.67:3000/historico/create HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": 31,
    "nome" : "Frediney",
    "profissao": "Tecnico de TI"
}

###

GET  http://10.60.46.67:3000/historico/read HTTP/1.1
content-type: application/json

###
GET  http://10.60.46.67:3000/historico/show/4 HTTP/1.1
content-type: application/json

###
PUT  http://10.60.46.67:3000/historico/update/4 HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": 30,
    "nome" : "Fred",
    "profissao": "Tecnico"
}

###
DELETE http://10.60.46.67:3000/historico/delete/1 HTTP/1.1
content-type: application/json