POST http://localhost:3000/lista_insumos HTTP/1.1
content-type: application/json

{
    "areia": "10kg",
    "pedra": "10kg",
    "cimento": "10kg",
    "pedrisco": "20kg"
}

###

GET http://localhost:3000/read_insumos HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/update_insumos/1 HTTP/1.1
content-type: application/json

{
    "areia": "10kg",
    "pedra": "10kg",
    "cimento": "10kg",
    "pedrisco": "40kg"
}

###

DELETE  http://localhost:3000/delete_insumos/2 HTTP/1.1
content-type: application/json
 